---
- hosts: 127.0.0.1
  connection: local

  vars:
    username: 'prem'
    password: 'sheldon'
    userhome: '/home/{{ username }}'

  tasks:
  - include: tasks/configure-software-arch.yaml
    when: ansible_facts["os_family"] == "Archlinux"

  - include: tasks/configure-software-ubuntu.yml
    when: ansible_facts["os_family"] == "Debian"

  # - include: tasks/configure-user.yaml


  # - name: DOTFILES - Copy dot files to user home
  #   become_user: "{{ username }}"
  #   copy:
  #     src: '/home/{{ username }}/dotfiles/config/'
  #     dest: '{{ userhome }}/'
