---
- hosts: 127.0.0.1
  connection: local

  vars:
    username: 'prem'
    password: ''
    userhome: '/home/{{ username }}'

  tasks:
  - include: tasks/configure-software-arch.yaml
    when: ansible_facts["os_family"] == "Archlinux"

  - include: tasks/configure-user.yaml
  
  # - name: Package Installation - Add yaourt repository
  #   lineinfile:
  #     path: '/etc/pacman.conf'
  #     regexp: '{{ item.regexp }}'
  #     line: '{{ item.line }}'
  #     state: present
  #   with_items:
  #    - { regexp: '\[archlinuxfr\]', line: '[archlinuxfr]' }
  #    - { regexp: 'SigLevel = Never', line: 'SigLevel = Never' }
  #    - { regexp: 'Server = http:\/\/repo.archlinux.fr\/\$arch', line: 'Server = http://repo.archlinux.fr/$arch' }

  - name: UI Tweak - Enable color for pacman
    lineinfile:
      path: '/etc/pacman.conf'
      regexp: '^#Color$'
      line: 'Color'

  - name: DOTFILES - Copy dot files to user home
    become_user: "{{ username }}"
    copy:
      src: '/home/{{ username }}/dotfiles/config/'
      dest: '{{ userhome }}/'
