- name: Package  Installation - Update packages.
  pacman:
    update_cache: true
    upgrade: true
  changed_when: false

- name: Package Installation - Common tools
  pacman:
    name:
      - git
      - wget
      - vim
      - zsh
      - thefuck
      - pulseaudio
      - playerctl
      - xbindkeys
      - lxappearance
      - xsettingsd
      - feh
      - neofetch
      - base-devel
      - python-pip
      - go
      - reflector
      - lightdm
      - lightdm-gtk-greeter
      - chromium
      - firefox
      - vlc
    state: present

- name: Package Installation - Media tools
  pacman:
    name:
      - noto-fonts
      - ttf-ubuntu-font-family
      - ttf-dejavu 
      - ttf-freefont 
      - ttf-liberation 
      - ttf-droid 
      - ttf-inconsolata
      - ttf-roboto
      - terminus-font 
      - ttf-font-awesome
    state: present
  changed_when: false

- name: Package Installation - Sound tools
  pacman:
    name:
      - alsa-utils
      - alsa-plugins
      - alsa-lib
      - pavucontrol
    state: present
  changed_when: false

- name: Package Installation - i3 Productivity tools
  pacman:
    name:
      - i3
      - xorg
      - xorg-xinit
      - compton
      - rxvt-unicode
      - ranger
      - rofi
      - conky
      - dmenu
      - urxvt-perls
      - perl-anyevent-i3
      - perl-json-xs
    state: present
  changed_when: false

- name: Package Installation - Media tools
  pacman:
    name:
      - flameshot
      - imagemagick
      - gimp
    state: present
  changed_when: false

- name: Install Python dependency
  pip:
    name: pexpect  

- name: UI Tweak - Enable color for pacman
  lineinfile:
    path: '/etc/pacman.conf'
    regexp: '^#Color$'
    line: 'Color'
