- name: Package  Installation - Update packages.
  pacman:
    update_cache: true
    upgrade: true
  changed_when: false

- name: Package Installation - Common tools
  pacman:
    name:
      - git
      - wget
      - vim
      - ranger
      - zsh
      - thefuck
      - pulseaudio
      - playerctl
      - xbindkeys
      - ttf-font-awesome
      - dmenu
      - rofi
      - compton
      - lxappearance
      - xsettingsd
      - feh
      - neofetch
      - base-devel
      - xorg
      - terminator
      - python-pip
      - go
    state: present

- name: Package Installation - Media tools
  pacman:
    name:
      - flameshot
      - imagemagick
      - gimp
    state: present
  changed_when: false

- name: Install Python dependency
  pip:
    name: pexpect  
