- name: User Configuration - Install Oh my zsh
  become: yes
  become_user: "{{ username }}"
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended

- name: User Configuration - Install zsh autosuggestions plugin
  become: yes
  become_user: "{{username}}"
  shell: git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

- name: User Configuration - Change default shell
  become: yes
  become_user: "{{ username }}"
  shell: echo "{{ password }}" | chsh -s $(which zsh)

- name: System Configuration - Default locale
  become: yes
  become_user: "{{ username }}"
  shell: echo "{{ password }}" | localectl set-locale LANG=en_US.UTF-8